services:
  jesker:
    image: 613895955229.dkr.ecr.eu-central-1.amazonaws.com/atomy/jesker:latest
    volumes:
      - .:/var/www
    working_dir: /var/www
    ports:
      - "28026:28026"
    environment:
      SERVER_PORT: 28026
      RCON_WEB: true
      RCON_PASSWORD: 'admin1337'
      FAKE_PLAYERS: '[{"name": "Robin", "steamId": "76561197960435530"},{"name": "jason", "steamId": "76561197978236369"}]'
      SERVER_NAME: 'EU Cool rust server'


